---
- name: Setup Web Service on Amazon EC2
  hosts: amazon_ec2
  become: true
  vars:
    ansible_python_interpreter: /usr/bin/python3
    web_service: httpd
    web_port: 80

  tasks:
    - name: Install web service package
      ansible.builtin.yum:
        name: "{{ web_service }}"
        state: present
      notify: start web service

    - name: Install firewalld
      ansible.builtin.yum:
        name: firewalld
        state: present
      notify: restart firewalld

    - name: Ensure firewalld is started and enabled
      ansible.builtin.service:
        name: firewalld
        state: started
        enabled: true

    - name: Allow HTTP port through firewalld
      ansible.builtin.firewalld:
        port: "{{ web_port }}/tcp"
        permanent: true
        state: enabled
        immediate: yes
      notify: reload firewalld

  handlers:
    - name: start web service
      ansible.builtin.service:
        name: "{{ web_service }}"
        state: started
        enabled: true

    - name: restart firewalld
      ansible.builtin.service:
        name: firewalld
        state: restarted

    - name: reload firewalld
      ansible.builtin.service:
        name: firewalld
        state: reloaded
