- name: Test EC2 Connection
  hosts: all
  become: false
  tasks:
    - name: Ping EC2 instance
      ansible.builtin.ping:

- name: Install tree utility on Amazon Linux
  hosts: all
  become: yes

  tasks:
    - name: Ensure tree is installed
      yum:
        name: tree
        state: present

- name: Install and start Tomcat on Amazon Linux
  hosts: all
  become: yes

  vars:
  tomcat_package: tomcat

  tasks:
            - name: Install Tomcat
              yum:
                name: "{{ tomcat_package }}"
                state: present
              notify: Start Tomcat

  handlers:
            - name: Start Tomcat
              service:
                name: "{{ tomcat_package }}"
                state: started
                enabled: yes