---
- name: Install and configure Nginx on EC2
  hosts: all
  become: yes

  tasks:
    - name: Install Nginx
      ansible.builtin.yum:
        name: nginx
        state: present

    - name: Ensure Nginx is enabled and started
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: yes

    - name: Allow HTTP service in firewalld
      become: true
      ansible.builtin.firewalld:
      service: http
      permanent: true
      state: enabled
      immediate: yes
      notify: Restart firewalld

  handlers:
    - name: Restart firewalld
      ansible.builtin.service:
        name: firewalld
        state: restarted