---
- name: Install and start Tomcat on EC2
  hosts: all
  become: yes

  vars:
    tomcat_package: tomcat9

  tasks:
    - name: Install Tomcat
      yum:
        name: "{{ tomcat_package }}"
        state: present
      notify: Start Tomcat

  handlers:
    - name: Start Tomcat
      service:
      name: "{{ tomcat_package }}"
      state: started
      enabled: yes

    - name: Allow Tomcat port in firewall
      ansible.builtin.firewalld:
      port: 8080/tcp
      permanent: yes
      state: enabled
      become: yes
      notify: Reload firewalld

    - name: Reload firewalld
      ansible.builtin.service:
      name: firewalld
      state: reloaded